spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?user=postgres&password=postgres&currentSchema=order_service

  jackson:
    property-naming-strategy: SNAKE_CASE

order-service:
  infra:
    delete-and-publish-outbox-message-batch-size: 5
