spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/postgres?user=postgres&password=postgres&currentSchema=order_service

  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization.write-dates-as-timestamps: false

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID:OBPAWSAKI}
      secretKey: ${AWS_SECRET_ACCESS_KEY:OBPAWSSAK}
      instanceProfile: false
      useDefaultAwsCredentialsChain: false
    region:
      auto: false
      static: us-east-1
    stack.auto: false

logging:
  level:
    com.amazonaws.util.EC2MetadataUtils: error

order-service:
  app:
    job:
      outbox-polling:
        fixed-rate-in-milli: 5000
        initial-delay-in-milli: 5000
        messages-to-delete: 5

  infra:
    aws:
      credentials:
        accessKey: ${cloud.aws.credentials.accessKey}
        secretKey: ${cloud.aws.credentials.secretKey}
      endpoint: http://${AWS_HOST:localhost}:4566
      region: ${cloud.aws.region.static}
      sns:
        subscription-created-topic: subscription-created
